### ISSUE TITLE
Invalid library in libinstpatch.pc

### ISSUE THREAD

**Issue by jjceresa** [swami/libinstpatch#10]
Actually in libinstpatch.pc, the following line describe two library: `libinstpatch-0.lib` and `m.lib`

`Libs: -L${libdir} -llibinstpatch-0 -lm`

Linking `libswami` target, to `libinstpatch` library leads to error: m.lib not found.

Please, does this option `-lm` really useful on Linux ?

**Comment by derselbst** [comment]
Correct, `-lm` is only required on Linux. This will probably be fixed once I've set up CI builds for Linux and Windows.

**Comment by jjceresa** [comment]
>This will probably be fixed once I've set up CI builds for Linux and Windows.

Does this shouldn't be fixed rather in CMakeLists.txt  that generate libinstpatch.pc from libinstpatch.pc.in ?

**Comment by derselbst** [comment]
Sure. I was just trying to say that I only see those windows related issues once CI builds are setup and take care of fixing them appropriately.

**Comment by jjceresa** [comment]
I will propose a PR to fix that.
